version: "2"

# Default rails .codeclimate.yml
#   https://raw.githubusercontent.com/rails/rails/master/.codeclimate.yml
# or you may opt to use:
#   https://raw.githubusercontent.com/IcaliaLabs/guides/master/best_practices/code-analysis/rails.codeclimate.yml

checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: false
  return-statements:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: false

plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-71
  reek:
    enabled: true
  brakeman:
    enabled: true

exclude_patterns:
  - "spec/"
  - "!spec/support/"
  - "config/"
  - "db/"
  - "vendor/"
  - "coverage/"
  - "bin/"
  - ".idea/"
  - "node_modules/"
  - "Guardfile"
